### ISSUE TITLE
Mapa Mental

### ISSUE THREAD

**Issue by Lissete7** [SistemasTecTlaxiaco/mapa-mental-web-3-Lissete7#1]
[Mapa mental Web 3.0_Lizzete L. G..pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-Lissete7/files/8455910/Mapa.mental.Web.3.0_Lizzete.L.G.pdf)

**Comment by christopheremv** [comment]
calificación:18/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
